<?php
// $Id$

/**
 * @file
 * Modulo para visualizar estado de remision de forma interna 
 * creado: Alejandro Leon - Norberto Villegas
 */

  define ('VE_DEBUG_MODE', true); 
  define ('VE_TIEMPO_RECARGA', 600); //segundos que guarda la ultima busqueda

 /** 
  * Implements hook_init() - Llamado de codigo antes de iniciar
  */
function visorentregas_init(){
  //llamar configuracion
  module_load_include('php', 'visorentregas', 'config\parametros');
  $_SESSION['visorentrega']['config'] = getParametros();
  return;
}


/**
 * Implements hook_menu().
 */
function visorentregas_menu() {
  // Module settings.
  /*$items['admin/config/visorentregas'] = array(
    'title' => 'Viajes Iron Module',
    'description' => 'viajes iron module configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('visorentregas_admin_settings_form'),
    'access arguments' => array('administrador modulo viajes'),
    'file' => 'visorentregas.admin.inc',
    'file path' => drupal_get_path('module', 'visorentregas'),
  );*/

  $items['visor/entrega'] = array(
    'title' => 'Buscador de Entregas',
    'description' => 'Buscador Drupal Entregas',
    'page callback' => 'generador_webpage_visor_buscador',
    'access arguments' => array('access content'),          //('administrador modulo viajes'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['visor/entrega/%'] = array(
    'title' => 'Estado de Entrega',
    'description' => 'Estado de Entrega - Toxement',
    'page callback' => 'generador_webpage_visor_entrega',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'page arguments' => array(2),
  );

  return $items;

}

/**
* Callbacks
* Llama a cada funcion que renderiza los formularios a los distintos enlaces
*/


/**
 * Callback para el buscador de entregas
 */
function generador_webpage_visor_buscador() {


  module_load_include('inc', 'visorentregas', 'presentacion/buscador_entregas');

  $build = array(
      'formulario_buscador' => drupal_get_form('buscador_entregas_form'),
  );

  //imprimir errores debug
  ve_mostrar_errores();

  return $build;
}

/**
 * Callback para generar el reporte de cada viaje 
 * @param {integer} viaje_id
 */
function generador_webpage_visor_entrega($entrega = NULL) {

  module_load_include('inc', 'visorentregas', 'presentacion/visor_entrega');

  //cargar datos del $viaje_id
  //consultar_viaje_por_id($entrega);
  //TODO hacer funcion que consulte el dato con el API
  
  $build = array(
    '#markup' => '<div class="mi-clase-css">opcion seleccionado ' . $entrega . '</div>',
  );

  // $build = array(
  //   'plantilla_viajes' => drupal_get_form('visor_entrega_render_form'),
  // );

  //imprimir errores debug si esta habilitado
  ve_mostrar_errores();

  return $build;
}




/* *
 * Callback para editar viajes, es llamado desde el formulario de reportes
 * /
function generador_webpage_edicion() {
  
  //Revisar si existe la variable local de viajes
  if ((!isset($_SESSION['visorentregas_data']['id'])) || ($_SESSION['visorentregas_data']['id'] == 'new')) {
    drupal_set_message('Error cargando información a editar, creando nuevo viaje', 'error');
    datos_en_blanco();
    $url_redirect = 'viajes';
    drupal_goto($url_redirect);
  }

  //Render de la pagina donde estan los formularios Iniciales
  $build = array(
      'formulario_viajes' => drupal_get_form('datos_viaje_formulario_form'),
  );

  //imprimir errores debug si esta habilitado
  mostrar_errores();
  
  return $build;
}


/ **
 * Callback para generar el formulario de busquedas de CUMPLIDOS
 * /
function generador_webpage_reporte_cumplidos() {

  module_load_include('inc', 'visorentregas', 'presentation/reportes_cumplidos/visorentregas_reporte_cumplidos_render');
  //render estructura de la pagina
  $build = array(
    'formulario_busqueda' => drupal_get_form('reporte_cumplidos_render_form'),
  );
  //imprimir errores debug si esta habilitado
  mostrar_errores();

  return $build;
}



/ **
 * Implementacion del hook permission para la administracion de roles
 * /
function visorentregas_permission() {
  $roles = array(
    'administrador modulo viajes' => array(
      'title' => t('Administrador del Modulo Viajes'),
      'description' => t('Puede generar nuevos viajes y visualizar los reportes'),
    ),
    'usuario modulo viajes' => array(
      'title' => t('Usuario basico Modulo Viajes'),
      'description' => t('Puede visualizar los reportes de los viajes'),
    ),
  );
  return $roles;
}*/

/**
 * Funcion para depuracion de datos o errores dentro de las funciones callback (DEBUG)
 * @param {varios} dato, string o similar para visualizar
 */
function ve_add_error($dato, $clave = '') {
  $errores = variable_get('viajesiron_error',array());
  if ($clave != '') { $errores[] = "clave: " . $clave; }
  $errores[] = $dato;
  variable_set('viajesiron_error', $errores);
}


/**
 * Funcion para desplegar todos los errores almacenados antes del llamado al callback
 */
function ve_mostrar_errores() {
  if (VE_DEBUG_MODE) {
    echo "<pre>";
    print_r(variable_get('viajesiron_error', 'no errores'));
    echo "</pre>";
    variable_del('viajesiron_error');
  }
}

