<?php
// $Id$

/**
 * @file
 * Modulo para visualizar estado de remision de forma interna 
 * creado: Alejandro Leon 03/05/2024
 * iconos: https://www.flaticon.es/iconos-gratis/
 */


 /** 
  * Implements hook_init() - Llamado de codigo antes de iniciar
  */
function visorentregas_init(){
  //llamar configuracion
  module_load_include('php', 'visorentregas', 'config/parametros');
  return;
}


/**
 * Implements hook_menu().
 */
function visorentregas_menu() {
  // Module settings.
  /*$items['admin/config/visorentregas'] = array(
    'title' => 'Viajes Iron Module',
    'description' => 'viajes iron module configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('visorentregas_admin_settings_form'),
    'access arguments' => array('administrador modulo viajes'),
    'file' => 'visorentregas.admin.inc',
    'file path' => drupal_get_path('module', 'visorentregas'),
  );*/

  $items['visor/entrega'] = array(
    'title' => 'Buscador de Entregas',
    'description' => 'Buscador Drupal Entregas',
    'page callback' => 'generador_webpage_visor_buscador',
    'access arguments' => array('usuario visorentrega'),    //hook permission
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}

/**
* Callbacks
* Llama a cada funcion que renderiza los formularios a los distintos enlaces
*/


/**
 * Callback para el buscador de entregas
 */
function generador_webpage_visor_buscador() {

  module_load_include('inc', 'visorentregas', 'presentacion/buscador_entregas');
  // form_load_include('inc', 'visorentregas', 'presentacion/buscador_entregas_submit');

  $build = array(
      'formulario_buscador' => drupal_get_form('buscador_entregas_form'),
  );

  //imprimir errores debug
  ve_mostrar_errores();

  return $build;
}


/**
 * Callback para generar el reporte de cada viaje 
 * @param {integer} viaje_id
 */
// function generador_webpage_visor_entrega($entrega = NULL) {

//   module_load_include('inc', 'visorentregas', 'presentacion/visor_entrega');

//   //cargar datos del $viaje_id
//   //consultar_viaje_por_id($entrega);
//   // hacer funcion que consulte el dato con el API
  
//   $build = array(
//     '#markup' => '<div class="mi-clase-css">opcion seleccionado ' . $entrega . '</div>',
//   );

//   // $build = array(
//   //   'plantilla_viajes' => drupal_get_form('visor_entrega_render_form'),
//   // );

//   //imprimir errores debug si esta habilitado
//   ve_mostrar_errores();

//   return $build;
// } /*

/**
 * Implementacion del hook permission para la administracion de roles
 */
function visorentregas_permission() {
  $roles = array(
    'usuario visorentrega' => array(
      'title' => t('Usuario para ver este modulo (visorentrega)'),
      'description' => t('Puede buscar y visualizar el estado de las remisiones'),
    ),
    // 'usuario modulo viajes' => array(
    //   'title' => t('Usuario basico Modulo Viajes'),
    //   'description' => t('Puede visualizar los reportes de los viajes'),
    // ),
  );
  return $roles;
}

/**
 * Funcion para depuracion de datos o errores dentro de las funciones callback (DEBUG)
 * @param {varios} dato, string o similar para visualizar
 */
function ve_add_error($dato, $clave = '') {
  $errores = variable_get('viajesiron_error',array());
  if ($clave != '') { $errores[] = "clave: " . $clave; }
  $errores[] = $dato;
  variable_set('viajesiron_error', $errores);
}


/**
 * Funcion para desplegar todos los errores almacenados antes del llamado al callback
 */
function ve_mostrar_errores() {
  if (VE_DEBUG_MODE) {
    echo "<pre>";
    print_r(variable_get('viajesiron_error', 'no errores'));
    echo "</pre>";
    variable_del('viajesiron_error');
  }
}

