<?php

// This is a autogenerated file:Embarques app.quicktype.io

class EstadoEntregaDTO {
    private $activityNum; // json:activity_num
    private $errorDTO; // json:errorDTO
    private $fechaPlanificadaEntrega; // json:fechaPlanificadaEntrega
    private $tracks; // json:tracks
    private $urlSoporte; // json:urlSoporte

    /**
     * @param string $activityNum
     * @param array $errorDTO
     * @param string $fechaPlanificadaEntrega
     * @param array $tracks
     * @param array $urlSoporte
     */
    public function __construct(
        $activityNum, 
        $errorDTO, 
        $fechaPlanificadaEntrega, 
        $tracks, 
        $urlSoporte
        ) {
            $this->activityNum = $activityNum;
            $this->errorDTO = $errorDTO;
            $this->fechaPlanificadaEntrega = $fechaPlanificadaEntrega;
            $this->tracks = $tracks;
            $this->urlSoporte = $urlSoporte;
        }
    
    public static function create($data) {
        $activityNum = $data['activity_num'];
        $errorDTO = $data['errorDTO'];
        $fechaPlanificadaEntrega = $data['fechaPlanificadaEntrega'];
        $tracks = array();
        foreach($data['tracks'] as $track){
            $track = Track::create($track);
            $tracks[] = $track;
        } 
        $urlSoporte = isset($data['urlSoporte']) ? $data['urlSoporte'] : array();
        return new self($activityNum, $errorDTO, $fechaPlanificadaEntrega, $tracks, $urlSoporte); 
    }

    public function toEntity() {
        module_load_include('php', 'visorentregas', 'dominio/entidades/estado_entrega');

        $fechaProcesoLogistico = 'En proceso logístico';
        $fechaEntregaTransportadora = 'Entrega a transportadora';
        $fechaEnTransito = 'En tránsito';
        $fechaEnReparto = 'Reparto';
        $fechaEntregado = 'Entregado';
        //$fechaEstimadaEntrega = 'fechaPlanificadaEntrega'; 

        $fechas = new FechasConsultaRemision();
        $fechas->setFechaProcesoLogistico($this->getEventoEspecifico($fechaProcesoLogistico));
        $fechas->setFechaEntregaTransportadora($this->getEventoEspecifico($fechaEntregaTransportadora));
        $fechas->setFechaEnTransito($this->getEventoEspecifico($fechaEnTransito));
        $fechas->setFechaEnReparto($this->getEventoEspecifico($fechaEnReparto));
        $fechas->setFechaEntregado($this->getEventoEspecifico($fechaEntregado));
        $fechas->setFechaEstimadaEntrega($this->getFechaPlanificadaEntrega());
        
        $estado = new EstadoEntrega();
        $estado->setFechas($fechas);
        $estado->setRemision($this->activityNum);
        $estado->setSoportes($this->getURLSoporte());

        return $estado;

    }

    public function getEventoEspecifico($evento) {
        foreach ($this->tracks as $track) {
            if ($track->getEvento() == $evento) {
                return $track->getFechaFormato();
            }
        }
        return false;
    } 

    /**
     * @return string
     */
    public function getActivityNum() {return $this->activityNum;}

    /**
     * @return ErrorDTO
     */
    public function getErrorDTO() {return $this->errorDTO;}

    /**
     * @return string
     */
    public function getFechaPlanificadaEntrega() {return $this->fechaPlanificadaEntrega;}

    /**
     * @return array
     */
    public function getTracks() {return $this->tracks;}

    /**
     * @return array
     */
    public function getURLSoporte() {return $this->urlSoporte;}

}

// This is a autogenerated file:Track
class Track {
    private $date; // json:date 
    private $eventKey; // json:event_key 
    private $evento; // json:evento 
    private $evidence; // json:evidence 
    private $fecha; // json:fecha 
    private $fechaFormato; // json:fechaFormato 
    private $horaFormato; // json:horaFormato 
    private $peso; // json:peso 
    private $source; // json:source 
    private $ultimaRegistrada; // json:ultimaRegistrada 

    /**
     * @param string $date
     * @param string $eventKey
     * @param string $evento
     * @param array $evidence
     * @param string $fecha
     * @param string $fechaFormato
     * @param string $horaFormato
     * @param int $peso
     * @param bool $source
     * @param bool $ultimaRegistrada
     */
    public function __construct(
        $date, 
        $eventKey, 
        $evento, 
        $evidence, 
        $fecha, 
        $fechaFormato, 
        $horaFormato, 
        $peso, 
        $source, 
        $ultimaRegistrada 
    ) {
        $this->date = $date;
        $this->eventKey = $eventKey;
        $this->evento = $evento;
        $this->evidence = $evidence;
        $this->fecha = $fecha;
        $this->fechaFormato = $fechaFormato;
        $this->horaFormato = $horaFormato;
        $this->peso = $peso;
        $this->source = $source;
        $this->ultimaRegistrada = $ultimaRegistrada;
    }

    public static function create($track) {
        $date = $track['date'];
        $eventKey = $track['event_key'];
        $evento = $track['evento'];
        $evidence = $track['evidence'];
        $fecha = $track['fecha'];
        $fechaFormato = $track['fechaFormato'];
        $horaFormato = $track['horaFormato'];
        $peso = $track['peso'];
        $source = $track['source'];
        $ultimaRegistrada = $track['ultimaRegistrada'];
        return new self (
            $date,
            $eventKey,
            $evento,
            $evidence,
            $fecha,
            $fechaFormato,
            $horaFormato,
            $peso,
            $source,
            $ultimaRegistrada
        );
    }

    /**
     * @return string
     */
    public function getDate() {return $this->date;}

    /**
     * @return string
     */
    public function getEventKey() {return $this->eventKey;}

    /**
     * @return string
     */
    public function getEvento() {return $this->evento;}

    /**
     * @return array
     */
    public function getEvidence() {return $this->evidence;}

    /**
     * @return string
     */
    public function getFecha() {return $this->fecha;}

    /**
     * @return string
     */
    public function getFechaFormato() {return $this->fechaFormato;}

    /**
     * @return string
     */
    public function getHoraFormato() {return $this->horaFormato;}

    /**
     * @return int
     */
    public function getPeso() {return $this->peso;}

    /**
     * @return bool
     */
    public function getSource() {return $this->source;}

    /**
     * @return bool
     */
    public function getUltimaRegistrada() {return $this->ultimaRegistrada;}

}
    

// // This is a autogenerated file:Evidence
// class Evidence {
//     private $type; // json:type
//     private $path; // json:path 

//     /**
//      * @param string $path
//      */
//     public function __construct(
//             string $path, 
//             string $type
//         ) {
//             $this->path = $path;
//             $this->type = $type;
//     }

//     /**
//      * @return string
//      */
//     public function getPath() {return $this->path;}

//     /**
//      * @return string
//      */
//     public function getType() {return $this->type;}

// }
